import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

// Create transporter
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: process.env.SMTP_PORT,
  secure: false, // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

export async function sendReportEmail(userData, excelBuffer) {
  const mailOptions = {
    from: `"Business Loan Calculator" <${process.env.SMTP_USER}>`,
    to: userData.email,
    subject: 'Your Business Loan Analysis Report',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #2563eb;">Your Business Loan Analysis Report</h2>
        
        <p>Dear ${userData.name},</p>
        
        <p>Thank you for using our Business Loan Calculator. Please find your detailed analysis report attached as an Excel file.</p>
        
        <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="margin-top: 0; color: #374151;">Report Contents:</h3>
          <ul style="color: #6b7280;">
            <li>Executive Summary with key metrics</li>
            <li>10-year financial projections</li>
            <li>Detailed funding source breakdown</li>
            <li>DSCR analysis and risk assessment</li>
          </ul>
        </div>
        
        <p>This report includes comprehensive analysis of your business acquisition financing structure, including:</p>
        <ul>
          <li>Cash flow projections for 10 years</li>
          <li>Debt service coverage ratios</li>
          <li>Loan amortization schedules</li>
          <li>Risk assessment metrics</li>
        </ul>
        
        <p>If you have any questions about your report or need additional analysis, please don't hesitate to contact us.</p>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
          <p style="color: #6b7280; font-size: 14px;">
            This report was generated by the Business Loan Calculator. 
            You have used ${userData.usageCount || 0} of your 5 free reports.
          </p>
        </div>
        
        <p>Best regards,<br>
        The Business Loan Calculator Team</p>
      </div>
    `,
    attachments: [
      {
        filename: `Business_Loan_Analysis_${userData.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.xlsx`,
        content: excelBuffer,
        contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      }
    ]
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Email sent successfully:', info.messageId);
    return info;
  } catch (error) {
    console.error('Email sending failed:', error);
    throw error;
  }
}

// Test email configuration
export async function testEmailConfig() {
  try {
    await transporter.verify();
    console.log('Email configuration is valid');
    return true;
  } catch (error) {
    console.error('Email configuration error:', error);
    return false;
  }
}